// Fill out your copyright notice in the Description page of Project Settings.


#include "LoginComp.h"
#include "HttpModule.h"
#include "IWebSocket.h"
#include "JsonObjectConverter.h"
#include "LogItemComp.h"
#include "UserStruct.h"
#include "WebSocketsModule.h"
#include "Blueprint/UserWidget.h"
#include "Components/EditableTextBox.h"
#include "Components/SizeBox.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/WrapBox.h"
#include "GameFramework/SpringArmComponent.h"
#include "Interfaces/IHttpRequest.h"
#include "Interfaces/IHttpResponse.h"
#include "PLAI/Item/GameInstance/WorldGi.h"
#include "PLAI/Item/ItemComp/InvenComp.h"
#include "PLAI/Item/Npc/NpcNet.h"
#include "PLAI/Item/TestPlayer/TestPlayer.h"
#include "PLAI/Item/TestPlayer/TraitStructTable/TraitStructTable.h"
#include "PLAI/Item/UI/Character/UIChaStat.h"
#include "PLAI/Item/UI/Inventory/EquipInven/EquipInven.h"
#include "PLAI/Item/UI/Inventory/ItemInven/ItemInven.h"
#include "PLAI/Item/UI/Main/UIChaMain.h"
#include "PLAI/Item/UI/Main/UiChaView.h"
#include "PLAI/Item/UI/Main/UIinitMain.h"
#include "PLAI/Item/UI/Main/UiSign.h"

// Sets default values for this component's properties
ULoginComp::ULoginComp()
{ PrimaryComponentTick.bCanEverTick = true; }

void ULoginComp::BeginPlay()
{
	Super::BeginPlay();
	
    if (FModuleManager::Get().IsModuleLoaded("WebSocket"))
    {
    	FModuleManager::Get().LoadModule("WebSocket");
    }
	
    TestPlayer = Cast<ATestPlayer>(GetOwner());
	
	if (TestPlayer->IsLocallyControlled())
	{
		if (UWorldGi* WorldGi = Cast<UWorldGi>(GetWorld()->GetGameInstance()))
		{
			// ìµœì´ˆ ê²Œì„ ì‹¤í–‰ í–ˆëŠ”ì§€
			if (WorldGi->bGameStart == false)
			{
				UiMain = CreateWidget<UUiMain>(GetWorld(),UiMainFactory);
				UiMain->AddToViewport(2);
				UiMain->LoginComp = this;
				UiMain->WbpUiSign->LoginComp = this;
			}
			else
			{
				if (WorldGi->bBattleReward == true)
				{
					UE_LOG(LogTemp, Warning, TEXT("LoginComp ì´ë¯¸ ì ‘ì†í•œ ìºë¦­í„° Gi UserFullInfo ë¶ˆëŸ¬ì˜¤ê¸°"));
					UserFullInfo = WorldGi->UserFullInfoGi;
					HttpMePost();
				
					FTimerHandle TimerHandle;
					GetWorld()->GetTimerManager().SetTimer(TimerHandle,[this]()
					{
						TestPlayer->InvenComp->TurnReward();
					},1.0,false);
				}
			}
		}
	}
}


// Called every frame
void ULoginComp::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
	
	if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
	{ if (PC->WasInputKeyJustPressed(EKeys::LeftMouseButton))
		{
		    FHitResult Hit;
		    PC->GetHitResultUnderCursor(ECC_Visibility, true, Hit);
		    if (Hit.bBlockingHit)
		    {
			    if (ANpcNet * NpcNet = Cast<ANpcNet>(Hit.GetActor()))
			    {
			    	if (bQuest == true)
			    	{
			    		NpcNet->OpenQuest();
			    		bQuest = false;
			    	}
			    	else
			    	{
			    		NpcNet->UIPost->RemoveFromParent();
			    		bQuest = true;
			    	}
			    }
		    }
		};
	}
}

void ULoginComp::HttpLoginPost()
{
    FNgrok Ngrok;
	
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest();

	httpRequest->SetURL(Ngrok.Ngrok + TEXT("/users/login"));
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));
	
	FLoginStruct LoginStruct;
	
	LoginStruct.email = UiMain->LoginId->GetText().ToString();
	LoginStruct.password = UiMain->LoginPw->GetText().ToString();

	FString JsonString;
	FJsonObjectConverter::UStructToJsonObjectString(LoginStruct, JsonString);
	httpRequest->SetContentAsString(JsonString);
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		FLoginStructGet LoginStructGetInit;
		FLoginStructGet LoginStructGet;
		if (bProcessedSuccessfully)
		{ FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp, Warning, TEXT("ë¡œê·¸ì¸ì»´í”„ í†µì‹ ì„±ê³µ ë¡œê·¸ì¸ JsonStringë¬´ì—‡ [%s]"), *JsonString);

			FJsonObjectConverter::JsonObjectStringToUStruct(JsonString, &LoginStructGet);
			if (LoginStructGetInit.user_id != LoginStructGet.user_id)
			{ OnLogin.ExecuteIfBound(true);
				UE_LOG(LogTemp, Error, TEXT("ë¡œê·¸ì¸ì»´í”„ í†µì‹ ì„±ê³µ ë¡œê·¸ì¸ User IdëŠ”? [%s]"),*LoginStructGet.user_id);
				UserFullInfo.user_id = LoginStructGet.user_id;
				// ë‹µë³€ì´ ì˜¨ ë”œë¦¬ê²Œì´íŠ¸ì—ë‹¤ê°€ meë¥¼ í•´ì•¼í• ë“¯
				UE_LOG(LogTemp, Display , TEXT("UiMain HttpLoginMe ë³´ë‚´ì"));
				UiMain->HttpLoginMe();
			}
			else
			{ OnLogin.ExecuteIfBound(false);
				UE_LOG(LogTemp, Warning, TEXT("ë¡œê·¸ì¸ì»´í”„ í†µì‹ ì„±ê³µ ë¡œê·¸ì¸ ì‹¤íŒ¨")); }
		}
	});
	httpRequest->ProcessRequest();
}


void ULoginComp::HttpSignPost()
{
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest();
	FNgrok Ngrok;
    FString url = FString::Printf(TEXT("%s/users/register"),*Ngrok.Ngrok);
	httpRequest->SetURL(url);
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));

	FLoginStruct LoginStruct;
	LoginStruct.email = UiMain->WbpUiSign->SignId->GetText().ToString();
	LoginStruct.password = UiMain->WbpUiSign->SignPw->GetText().ToString();

	FString JsonString;
	FJsonObjectConverter::UStructToJsonObjectString(LoginStruct, JsonString);
	httpRequest->SetContentAsString(JsonString);
	
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		if (bProcessedSuccessfully)
		{
			FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp,Warning,TEXT("ë¡œê·¸ì¸ì»´í”„ ê°€ì…ìš”ì²­ ì„±ê³µ %s ë‹µë³€ì½”ë“œ %d"),*JsonString,HttpResponse->GetResponseCode());
			if (UiMain->WbpUiSign)
			{
				UiMain->WbpUiSign->SignCompleteBox->SetVisibility(ESlateVisibility::Visible);
				if (HttpResponse->GetResponseCode() == 200)
				{
					// UiMain->WbpUiSign->SignCompleteBox->SetVisibility(ESlateVisibility::Visible);
					UiMain->WbpUiSign->bSingComplete->SetText(FText::FromString(TEXT("ê°€ì… ì™„ë£Œ")));
				}
				else
				{
					// UiMain->WbpUiSign->SignCompleteBox->SetVisibility(ESlateVisibility::Visible);
					UiMain->WbpUiSign->bSingComplete->SetText(FText::FromString(TEXT("ê°€ì… ì‹¤íŒ¨")));
					UiMain->WbpUiSign->bSingCompleteDetail->SetText(FText::FromString(JsonString));
				}
			}
		}
		else
		{
			UE_LOG(LogTemp,Warning,TEXT("ë¡œê·¸ì¸ì»´í”„ ê°€ì…ìš”ì²­ ì‹¤íŒ¨ %d"),HttpResponse->GetResponseCode());
		}
	});
	httpRequest->ProcessRequest();
}

void ULoginComp::Server_HttpMePost_Implementation()
{
	Client_HttpMePost();
}

void ULoginComp::Client_HttpMePost_Implementation()
{
	HttpMePost();
}

void ULoginComp::HttpMePost()
{
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest(); FNgrok Ngrok;
	FString url = FString::Printf(TEXT("%s/me/"),*Ngrok.Ngrok);

	httpRequest->SetURL(url);
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));

	FString JsonString;
	FMeStruct MeStruct;
	
	MeStruct.user_id = UserFullInfo.user_id;
	
	FJsonObjectConverter::UStructToJsonObjectString(MeStruct,JsonString);
	httpRequest->SetContentAsString(JsonString);
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		if (bProcessedSuccessfully)
		{
			FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp,Warning,TEXT("ë¡œê·¸ì¸ì»´í”„ ë‚˜ì˜ì •ë³´ GetAsContetAsStringëœ ì œì´ìŠ¨ê°’ ì„±ê³µ %s"),*JsonString);
			
			if (JsonString.IsEmpty())
			{
				UE_LOG(LogTemp, Error, TEXT("Login Comp // ì„œë²„ ì‘ë‹µì€ ì„±ê³µí–ˆì§€ë§Œ ë‚´ìš©ì´ ë¹„ì—ˆìŠµë‹ˆë‹¤."));
				return;
			}
			// 2. JSON â†’ Struct íŒŒì‹± ì‹œë„
			if (!FJsonObjectConverter::JsonObjectStringToUStruct(JsonString, &UserFullInfo))
			{
				UE_LOG(LogTemp, Error, TEXT("Login Comp // JSON íŒŒì‹± ì‹¤íŒ¨: êµ¬ì¡°ì²´ ë³€í™˜ì— ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤."));
				return;
			}
			// 3. íŒŒì‹± ì„±ê³µí–ˆë”ë¼ë„, í•„ìˆ˜ ê°’ì´ ë“¤ì–´ìˆëŠ”ì§€ ìœ íš¨ì„± ê²€ì‚¬
			if (UserFullInfo.character_info.character_id.IsEmpty())
			{
				UE_LOG(LogTemp, Error, TEXT("Login Comp // UserFullInfo í•„ìˆ˜ ê°’ì´ ë¹„ì–´ ìˆìŒ (character_id ì—†ìŒ)."));
				return;
			}
			
			UE_LOG(LogTemp,Warning,TEXT("ë¡œê·¸ì¸ì»´í”„ ë‚˜ì˜ì •ë³´ ì¡°íšŒ ì„±ê³µ %s"),*JsonString);
			FJsonObjectConverter::JsonObjectStringToUStruct(JsonString, &UserFullInfo);
			// FString GetJson;
			// FJsonObjectConverter::UStructToJsonObjectString(UserFullInfo,GetJson);
			// UE_LOG(LogTemp,Warning,TEXT("ë¡œê·¸ì¸ì»´í”„ ë‚˜ì˜ì •ë³´ ì¡°íšŒ Jsonë³€í™˜ %s"),*GetJson);

			if (UiMain)
			{
				UiMain->Wbp_UIChaMain->SetUiChaStat(&UserFullInfo);
				TestPlayer->InvenComp->MenuInven->Wbp_UIChaStat->SetUiChaStat(&UserFullInfo);
				FUserFullInfo InitUserFullInfo;
				
				// if (InitUserFullInfo.character_info.character_name != UserFullInfo.character_info.character_name)
				// {
				// 	UE_LOG(LogTemp,Warning,TEXT("LoginComp ìƒì„±ëœ ìºë¦­í„° ë‹‰ë„´ì€? %s"),*UserFullInfo.character_info.character_name);
				// 	UiMain->Wbp_UiInitMain->RemoveFromParent();
				// }else
				// {
				// 	UE_LOG(LogTemp,Warning,TEXT("LoginComp ìƒì„±ë˜ì§€ ì•Šì€ ìºë¦­í„° ì…ë‹ˆë‹¤? %s"),*UserFullInfo.character_info.character_name);
				// }
			}
			else
			{
				UE_LOG(LogTemp,Warning,TEXT("LoginComp í„´ì œí›„ ë„˜ì–´ì˜¤ë©´ UiMainì´ ì—†ì–´ìš”"));
			}
			
			LoadEquipItem();
			LoadInvenItem();
			
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->NameCha->SetText
			(FText::FromString(UserFullInfo.character_info.character_name));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->JobCha->SetText
			(FText::FromString(UserFullInfo.character_info.job));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->LevCha->SetText
			(FText::AsNumber(UserFullInfo.character_info.level));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->ExpCha->SetText
			(FText::AsNumber(UserFullInfo.character_info.current_exp));
			TestPlayer->InvenComp->MenuInven->Wbp_ChaView->MaxExpCha->SetText
			(FText::AsNumber(UserFullInfo.character_info.max_exp));

			if (TestPlayer && UserFullInfo.character_info.position.x != 0)
			{
				TestPlayer->SetActorLocation(FVector(UserFullInfo.character_info.position.x,
					UserFullInfo.character_info.position.y,UserFullInfo.character_info.position.z));
			}
			else
			{
				UE_LOG(LogTemp,Warning,TEXT("LoginComp ìºë¦­í„° ìœ„ì¹˜ ë¶ˆëŸ¬ì˜¤ë ¤ë‹¤ TestPlayer ë˜ëŠ” X ì¢Œí‘œ 0ì„"))
			}
		}
	});
	httpRequest->ProcessRequest();
}

void ULoginComp::LoadEquipItem()
{
	for (int32 i = 0; i < UserFullInfo.equipment_info.item_list.Num() ; i++)
	{
		for (UWidget* Widget : TestPlayer->InvenComp->MenuInven->WBP_EquipInven->LeftBox->GetAllChildren())
		{
			if (USlotEquip* SlotEquip = Cast<USlotEquip>(Widget)) // 1ë²ˆë¶€í„° 5ë²ˆê¹Œì§€ ìŠ¬ë¡¯ ëˆë‹¤
			{
				TArray<FName>RawNames = SlotEquip->ItemTable->GetRowNames();
			    for (FName RawName : RawNames)
			    {
			    	FItemStructTable* ItemStructTable = SlotEquip->ItemTable->FindRow<FItemStructTable>(RawName,"ë¡œê·¸ì¸ì»´í”„");
			    	if (UserFullInfo.equipment_info.item_list[i].item_id == RawName &&
			    		static_cast<int32>(SlotEquip->SlotType) == ItemStructTable->ItemIndex)
			    	{
			    		TestPlayer->InvenComp->Server_EquipItem(*ItemStructTable,SlotEquip->SlotType);
			    		SlotEquip->ItemStructTable = *ItemStructTable;
			    		SlotEquip->SlotImageUpdate();
			    		break;
			    	}
			    }
			}
		}
	}
}

void ULoginComp::LoadInvenItem()
{
	if (!TestPlayer -> IsLocallyControlled()){return;}
	
	// TestPlayer->InvenComp->SetGold(UserFullInfo.inventory_info.gold);
	TestPlayer->InvenComp->SetGold(0);
	if (USlot* Slot = Cast<USlot>(TestPlayer->InvenComp->MenuInven->WBP_ItemInven->WrapBox->GetChildAt(0)))
	{
		TArray<FName>RawNames = Slot->ItemTable->GetRowNames();
		for (int32 i = 0; i < UserFullInfo.inventory_info.item_list.Num(); i++)
		{
			for (FName RawName : RawNames)
			{
				FItemStructTable* ItemStructTable = Slot->ItemTable->FindRow<FItemStructTable>(RawName,"LoginComp");
				if (ItemStructTable->Item_Id == UserFullInfo.inventory_info.item_list[i].item_id)
				{
					USlot* SlotInvel = Cast<USlot>(TestPlayer->InvenComp->MenuInven->
						WBP_ItemInven->WrapBox->GetChildAt(i));
					SlotInvel->ItemStructTable = *ItemStructTable;
					SlotInvel->SlotImageUpdate();
				}
			}
		}
	}
}



void ULoginComp::HttpCreatePost(FString CharacterName)
{
	FHttpRequestRef httpRequest = FHttpModule::Get().CreateRequest();
	FNgrok Ngrok;

	FString Endpoint = FString::Printf(TEXT("%s/characters/create"), *Ngrok.Ngrok);
	httpRequest->SetURL(Endpoint);
	
	httpRequest->SetVerb("POST");
	httpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json"));

	FCreateStruct CreateStruct;
	
	CreateStruct.user_id = UserFullInfo.user_id;
	CreateStruct.character_name = CharacterName;

	FString JsonString;
	FJsonObjectConverter::UStructToJsonObjectString(CreateStruct, JsonString);
	UE_LOG(LogTemp,Display,TEXT("ë¡œê·¸ì¸ì»´í”„ Json String ì˜ê¸°ì „ : %s"),*JsonString);
	httpRequest->SetContentAsString(JsonString);
	
	httpRequest->OnProcessRequestComplete().BindLambda([this](FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bProcessedSuccessfully)
	{
		if (bProcessedSuccessfully)
		{
			FCreateStructGet CreateStructGet;
			FString JsonString = HttpResponse->GetContentAsString();
			UE_LOG(LogTemp,Warning,TEXT("ë¡œê·¸ì¸ì»´í”„ ìºë¦­í„° ìƒì„± ì„±ê³µ %s"),*JsonString);
			
			FJsonObjectConverter::UStructToJsonObjectString(CreateStructGet,JsonString);
			character_id = CreateStructGet.character_id;
		}
		else
		{
			UE_LOG(LogTemp,Warning,TEXT("ë¡œê·¸ì¸ì»´í”„ ìºë¦­í„° ìƒì„± ì‹¤íŒ¨ %d"),HttpResponse->GetResponseCode());
		}
	});
	httpRequest->ProcessRequest();
}

void ULoginComp::ConnectWebSocket()
{
	const FString URL = FString::Printf(TEXT(
		"wss://919e-221-148-189-129.ngrok-free.app/service1/ws/characters/create/%s"),*UserFullInfo.user_id);
	
	UE_LOG(LogTemp,Warning,TEXT("LoginComp WebSocket ì—°ê²°ëœ ì£¼ì†Œ[%s]"),*URL)
	const FString Protocol = TEXT("");
	
	WebSocket = FWebSocketsModule::Get().CreateWebSocket(URL, Protocol);
	// ì—°ê²° ì„±ê³µ
	WebSocket->OnConnected().AddUObject(this, &ULoginComp::OnWebSocketConnected);
	// ë©”ì‹œì§€ ìˆ˜ì‹ 
	WebSocket->OnMessage().AddUObject(this, &ULoginComp::OnWebSocketMessage);
	// ì—ëŸ¬ ì²˜ë¦¬
	WebSocket->OnConnectionError().AddUObject(this, &ULoginComp::OnWebSocketConnectionError);
	// ì¢…ë£Œ ì²˜ë¦¬
	WebSocket->OnClosed().AddUObject(this, &ULoginComp::OnWebSocketClosed);
	// ì‹¤ì œ ì—°ê²° ì‹œë„
	WebSocket->Connect();
}

void ULoginComp::OnWebSocketConnected()
{
	UE_LOG(LogTemp, Log, TEXT("âœ… LoginComp WebSocket Connected!"));
}

void ULoginComp::OnWebSocketMessage(const FString& Msg)
{
	UE_LOG(LogTemp, Warning, TEXT("LoginComp ì›¹ì†Œì¼“ ë©”ì‹œì§€ [%s]"), *Msg);
	UiMain->Wbp_UiInitMain->InitResponse->SetText(FText::FromString(Msg));
}

void ULoginComp::OnWebSocketConnectionError(const FString& Error)
{
	UE_LOG(LogTemp, Warning, TEXT("LoginComp ì›¹ì†Œì¼“ ì—ëŸ¬ [%s]"), *Error);
}

void ULoginComp::SendInitStringWebSocket(const FString& Message)
{
	if (WebSocket.IsValid() && WebSocket->IsConnected())
	{
		WebSocket->Send(Message);
		UE_LOG(LogTemp, Log, TEXT("â–¶ Sent via WS: %s"), *Message);
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("WebSocket not connected!"));
	}
}

void ULoginComp::OnWebSocketClosed(int32 StatusCode, const FString& Reason, bool bWasClean)
{
	UE_LOG(LogTemp,Warning,TEXT("ğŸ”’LoginCOmp ì›¹ì†Œì¼“ Closed: Code=%d Reason=%s Clean=%d"), StatusCode, *Reason, bWasClean);
}



// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::C)) // C ìºë¦­í„° ìƒì„± ìš”ì²­
// 	{   UE_LOG(LogTemp,Display,TEXT("Input C ìºë¦­í„° ìƒì„± ìš”ì²­ Key JustPressed"));
// 	    HttpCreatePost();
// 	}
// }

// DrawDebugString(GetWorld(),TestPlayer->GetActorLocation() + FVector(0, 0, 100),
// FString::Printf(TEXT("LoginComp ë‚˜ì˜ UserId [%s] \n "
// 				              "LoginComp ë‚˜ì˜ CharacterId [%s]"),*UserFullInfo.user_id, *UserFullInfo.character_info.character_id),
// 				  nullptr,FColor::Red,0.f,false);

// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::M)) // M ìºë¦­í„° ìƒì„± ë‚´ ì •ë³´ ìš”ì²­
// {   UE_LOG(LogTemp,Display,TEXT("Input M ë‚´ ì •ë³´ ì£¼ì…ˆ Key JustPressed"));
// 	HttpMePost();
// }
// }

// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::N)) // N ë‚´ì•„ì´í…œ ì£¼ì…ˆ
// 	{   UE_LOG(LogTemp,Display,TEXT("Input N ì¥ë¹„ì•„ì´í…œ ë¶™ì´ê¸° í…ŒìŠ¤íŠ¸"));
// 	if (UWorldGi* WorldGi = Cast<UWorldGi>(GetWorld()->GetGameInstance()))
// 	{
// 		WorldGi->EquipActor(TestPlayer);
// 	}
// 	}
// }

// if (APlayerController* PC = Cast<APlayerController>(TestPlayer->GetController()))
// { if (PC->WasInputKeyJustPressed(EKeys::B)) // B ì›¹ì†Œì¼“ì—°ê±¸
// {
// 	ConnectWebSocket();
// 	UE_LOG(LogTemp,Display,TEXT("Input B ì›¹ì†Œì¼“ ì—°ê²° Key JustPressed"));
// }
// }